import type { Macro } from '../types/macro';

export const DEFAULT_ENCLAVE_MACROS: Macro[] = [
  {
    id: 'macro_dawn_sync',
    name: 'Executive Dawn Sync',
    phrase: 'morning briefing',
    description:
      'Synchronizes portfolio state, notifies Malik Strategy, and recites morning brief.',
    category: 'operations',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'kba_routine',
        label: 'KBA State Sync Routine',
        payload: 'kba kba_sync_dawn',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'voice_command',
        label: 'Dispatch Malik Strategy Brief',
        payload: 'remind Malik daily KPI synthesis ready',
        delayMs: 250,
      },
      {
        id: 'step_3',
        type: 'speak_feedback',
        label: 'Voice Response',
        payload:
          'Morning briefing initialized. Portfolio synchronized and Malik Strategy briefed, Sovereign.',
        delayMs: 200,
      },
    ],
  },
  {
    id: 'macro_emergency_maint',
    name: 'Emergency Maintenance Dispatch',
    phrase: 'emergency maintenance',
    description:
      'Dispatches emergency plumbing work order and routes priority ticket to Gavin Forge.',
    category: 'operations',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'property_dispatch',
        label: 'Dispatch Emergency Plumber',
        payload: JSON.stringify({
          unit: 'Unit 4B',
          issue: 'Critical pipe leakage',
          priority: 'CRITICAL',
        }),
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'knight_dispatch',
        label: 'Assign to Gavin Forge',
        payload: 'Assign urgent plumbing work order ticket for Unit 4B',
        knightId: 'MAINT_005',
        delayMs: 200,
      },
      {
        id: 'step_3',
        type: 'client_navigation',
        label: 'Navigate to Properties',
        payload: 'Properties',
        delayMs: 150,
      },
      {
        id: 'step_4',
        type: 'speak_feedback',
        label: 'Confirm Dispatch',
        payload:
          'Emergency plumber dispatched to Unit 4B. Priority ticket assigned to Gavin Forge.',
        delayMs: 200,
      },
    ],
  },
  {
    id: 'macro_reserve_deposit',
    name: 'Treasury Reserve Ingestion',
    phrase: 'deposit treasury reserve',
    description:
      'Posts a $75,000 balanced ledger transaction into Vault Omega with HITL safety gate.',
    category: 'financial',
    enabled: true,
    safetyTier: 'hitl_confirm',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'voice_command',
        label: 'Post Balanced Transaction to Vault',
        payload: 'add transaction 75000',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'speak_feedback',
        label: 'Vault Response',
        payload: 'Posting balanced treasury entry of $75,000 to Vault Omega.',
        delayMs: 200,
      },
    ],
  },
  {
    id: 'macro_acoustic_calibration',
    name: 'Acoustic Stream & Bitrate Check',
    phrase: 'calibrate acoustic stream',
    description:
      'Runs audio audit routine, checks Leo Sterling acoustic metrics, and opens streaming tab.',
    category: 'knights',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'kba_routine',
        label: 'Audit Audio Stream',
        payload: 'kba kba_audit_stream',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'client_navigation',
        label: 'Navigate to Streaming Watch',
        payload: 'Streaming',
        delayMs: 150,
      },
      {
        id: 'step_3',
        type: 'speak_feedback',
        label: 'Acoustic Status',
        payload: 'Acoustic telemetry calibrated. Bitrate nominal at 320kbps lossless.',
        delayMs: 200,
      },
    ],
  },
  {
    id: 'macro_enclave_lockdown',
    name: 'Enclave Lockdown & Rezero',
    phrase: 'emergency lockdown',
    description:
      'Executes KBA rezero protocol, purges volatile buffers, and locks down tenant perimeter.',
    category: 'security',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'kba_routine',
        label: 'Execute Master Rezero',
        payload: 'kba kba_rezero_master',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'voice_command',
        label: 'Notify CEO of Lockdown',
        payload: 'remind Malik enclave rezeroed under Sovereign directive',
        delayMs: 250,
      },
      {
        id: 'step_3',
        type: 'speak_feedback',
        label: 'Security Audio',
        payload: 'Enclave rezeroed. Memory buffers flushed and security locks engaged.',
        delayMs: 200,
      },
    ],
  },
  {
    id: 'macro_open_vault',
    name: 'Open Memory Vault',
    phrase: 'open vault',
    description: 'Navigates to the secure biometric memory boundary vault.',
    category: 'security',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'client_navigation',
        label: 'Navigate to Vault',
        payload: 'vault',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'speak_feedback',
        label: 'Voice Response',
        payload: 'Accessing memory vault.',
        delayMs: 100,
      },
    ],
  },
  {
    id: 'macro_refresh_dashboard',
    name: 'Refresh Dashboard',
    phrase: 'refresh dashboard',
    description: 'Resets the workspace view back to the main Overview dashboard.',
    category: 'operations',
    enabled: true,
    safetyTier: 'auto',
    executionCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    steps: [
      {
        id: 'step_1',
        type: 'client_navigation',
        label: 'Navigate to Overview',
        payload: 'overview',
        delayMs: 0,
      },
      {
        id: 'step_2',
        type: 'speak_feedback',
        label: 'Voice Response',
        payload: 'Dashboard refreshed.',
        delayMs: 100,
      },
    ],
  },
];

